// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const font = { url, y: 0, x: 0, w: 144, h: 5, };
export const cell = { url, y: 5, x: 0, w: 19, h: 19, };
export const arrow_right = { url, y: 0, x: 148, w: 3, h: 3, };
export const arrow_left = { url, y: 0, x: 151, w: 3, h: 3, };
export const arrow_down = { url, y: 0, x: 154, w: 3, h: 3, };
export const arrow_up = { url, y: 0, x: 157, w: 3, h: 3, };
export const cell_halt = { url, y: 5, x: 19, w: 19, h: 19, };
export const pointer = { url, y: 5, x: 57, w: 19, h: 19, };
export const pointer_idle = { url, y: 5, x: 76, w: 19, h: 19, };
export const cursor = { url, y: 5, x: 95, w: 7, h: 9, };
export const cell_register = { url, y: 5, x: 38, w: 19, h: 19, };